language: python
sudo: false
matrix:
  include:
  - name: "3.6 Regression Test"
    python: 3.6
    os: linux
  - name: "3.7 Regression Test"
    python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install -r dev_requirements.txt
script:
  - python -m unittest -v tests.regression.regression.TestRegression.run_all_regression_tests